# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_issue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.IssueState'),
            preserve_default=False,
        ),
    ]
