# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:42
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group, Permission, User


def create_group_permissions(apps, schema_editor):
    superuser, created = Group.objects.get_or_create(name='superuser')
    staff, created = Group.objects.get_or_create(name='staff')
    permissions = []
    permissions.append(Permission.objects.get(codename='add_issuestate'))
    permissions.append(Permission.objects.get(codename='change_issuestate'))
    permissions.append(Permission.objects.get(codename='delete_issuestate'))
    permissions.append(Permission.objects.get(codename='add_issuecategory'))
    permissions.append(Permission.objects.get(codename='change_issuecategory'))
    permissions.append(Permission.objects.get(codename='delete_issuecategory'))
    permissions.append(Permission.objects.get(codename='add_issue'))
    permissions.append(Permission.objects.get(codename='change_issue'))
    permissions.append(Permission.objects.get(codename='delete_issue'))

    for permission in permissions:
        superuser.permissions.add(permission)
        superuser.permissions.add(permission)

    s_user = User.objects.create_user('suTest', password='Password1*')
    s_user.is_staff = True
    s_user.groups.add(superuser)
    User.objects.create_user('staffTest', password='Password1*').groups.add(staff)

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_issue_state'),
    ]

    operations = [
        migrations.RunPython(create_group_permissions),
    ]
